import Translate from '@docusaurus/Translate';
import React from 'react';

export const tabs = [
  {
    id: 'rollback',
    label: <Translate id="demo.terminal.tab.rollback">Snapshot Rollback</Translate>,
    lines: [
      { text: '$ sudo nixos-rebuild switch', type: 'command', delay: 800 },
      { text: 'building Nix...', type: 'output', delay: 600 },
      { text: 'error: builder for /nix/store/abc...drv failed with exit code 1', type: 'error', delay: 800 },
      { text: 'error: build of /nix/store/xyz...drv failed', type: 'error', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ snapper list', type: 'command', delay: 800 },
      { text: ' # | Type   | Pre # | Date                    | Description', type: 'output', delay: 200 },
      { text: '---+--------+-------+-------------------------+-------------', type: 'output', delay: 200 },
      { text: ' 0 | single |       |                         | current', type: 'output', delay: 200 },
      { text: '42 | pre    |       | 2024-03-15 14:30:00     | pre-rebuild', type: 'output', delay: 200 },
      { text: '43 | post   |    42 | 2024-03-15 14:31:22     | post-rebuild', type: 'output', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ sudo snapper undochange 42..43', type: 'command', delay: 800 },
      { text: 'undoing change 42..43', type: 'output', delay: 600 },
      { text: 'Successfully reverted to snapshot 42', type: 'success', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ sudo nixos-rebuild switch', type: 'command', delay: 800 },
      { text: 'building Nix...', type: 'output', delay: 600 },
      { text: 'activating the configuration...', type: 'output', delay: 600 },
      { text: 'setting up /etc...', type: 'output', delay: 400 },
      { text: 'system activation successful', type: 'success', delay: 400 },
    ],
  },
  {
    id: 'openclaw',
    label: <Translate id="demo.terminal.tab.openclaw">OpenClaw AI Ops</Translate>,
    lines: [
      { text: '$ openclaw status', type: 'command', delay: 800 },
      { text: '[INFO] OpenClaw agent v0.3.2 running', type: 'output', delay: 400 },
      { text: '[WARN] Anomaly detected: nginx response time > 5s', type: 'error', delay: 800 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ openclaw analyze --service nginx', type: 'command', delay: 800 },
      { text: '[AI] Analyzing service: nginx', type: 'output', delay: 600 },
      { text: '[AI] Root cause: upstream backend timeout (PostgreSQL)', type: 'output', delay: 800 },
      { text: '[AI] Classification: Tier 1 — service restart recommended', type: 'success', delay: 600 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ openclaw snapshot --pre-remediation', type: 'command', delay: 800 },
      { text: '[SNAP] Created Btrfs snapshot #44: pre-remediation', type: 'success', delay: 600 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ openclaw execute --tier 1 --action restart-postgresql', type: 'command', delay: 800 },
      { text: '[EXEC] Restarting postgresql.service...', type: 'output', delay: 1000 },
      { text: '[EXEC] Service restarted successfully', type: 'success', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ openclaw verify --service nginx', type: 'command', delay: 800 },
      { text: '[VERIFY] nginx response time: 120ms ✓', type: 'success', delay: 600 },
      { text: '[VERIFY] All health checks passed ✓', type: 'success', delay: 400 },
    ],
  },
  {
    id: 'btrfs',
    label: <Translate id="demo.terminal.tab.btrfs">Btrfs Snapshots</Translate>,
    lines: [
      { text: '$ sudo btrfs subvolume snapshot / /.snapshots/manual-backup', type: 'command', delay: 800 },
      { text: "Create a snapshot of '/' in '/.snapshots/manual-backup'", type: 'success', delay: 600 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ sudo btrfs subvolume list /', type: 'command', delay: 800 },
      { text: 'ID 256 gen 1420 top level 5 path @', type: 'output', delay: 200 },
      { text: 'ID 257 gen 1420 top level 5 path @home', type: 'output', delay: 200 },
      { text: 'ID 258 gen 1418 top level 256 path .snapshots/manual-backup', type: 'output', delay: 200 },
      { text: 'ID 259 gen 1400 top level 256 path .snapshots/pre-rebuild', type: 'output', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ sudo btrfs send /.snapshots/pre-rebuild | sudo btrfs receive /backup/', type: 'command', delay: 800 },
      { text: 'At subvol /.snapshots/pre-rebuild', type: 'output', delay: 600 },
      { text: 'At subvol /backup/pre-rebuild', type: 'success', delay: 400 },
      { text: '', type: 'output', delay: 300 },
      { text: '$ btrfs filesystem df /', type: 'command', delay: 800 },
      { text: 'Data, single: total=24.00GiB, used=18.54GiB', type: 'output', delay: 200 },
      { text: 'System, single: total=32.00MiB, used=16.00KiB', type: 'output', delay: 200 },
      { text: 'Metadata, single: total=1.00GiB, used=512.00MiB', type: 'output', delay: 200 },
      { text: 'GlobalReserve, single: total=64.00MiB, used=0.00B', type: 'output', delay: 200 },
    ],
  },
];
